kind: Service
apiVersion: v1
metadata:
  name:  nodeJs
  labels:
    app: nodeJs
spec:
  selector:
    app:  nodeJs
  ports:
    - name:  server
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeJs
  labels:
    app: nodeJs
spec:
  selector:
    matchLabels:
      app: nodeJs
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nodeJs
    spec:
      containers:
        - name: server
          image: 'placeholder'
          ports:
            - containerPort: 8080